### ISSUE TITLE
How do you create a Post resource?

### ISSUE THREAD

**Issue by jonwhittlestone** [InactiveProjects/limoncello-illuminate#4]
In Limoncello collins, when posting to http://limoncello-collins.dev/api/v1/posts

the response is always

`{
  "errors": [
    {
      "title": "Unauthorized."
    }
  ]
}`

I use the token that I have previously obtained by hitting the authenticate route.

What must I do to Authenticate? I am able to successfully obtain the list of posts, or list of Boards etc.

Thanks

**Comment by neomerx** [comment]
Have you seen [postman commands collection](https://app.getpostman.com/run-collection/064046759f3d14d4def7#?env%5Blimoncello%5D=W3sia2V5Ijoic2VydmVyIiwidmFsdWUiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJ0eXBlIjoidGV4dCIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoidG9rZW4iLCJ0eXBlIjoidGV4dCIsInZhbHVlIjoie1wiaWRfdXNlclwiOjEsXCJzZWNyZXRcIjpcIk1KaXpFVnJQUk96Qk83OXZcIn0iLCJlbmFibGVkIjp0cnVlfV0=)? It's on the frontpage. With postman (kinda gui for curl) you need to get auth token first (it's all configurable and made only for illustration purposes)

![image](https://cloud.githubusercontent.com/assets/10420662/15230382/064b1fdc-189e-11e6-85f9-c4154dd5366c.png)

auth request body

![image](https://cloud.githubusercontent.com/assets/10420662/15230579/07e37ea6-189f-11e6-8594-d542da167920.png)

and you good to go to create new items

![image](https://cloud.githubusercontent.com/assets/10420662/15230493/a71efeb0-189e-11e6-9e19-e48957bb3c13.png)

don't forget to add auth token
![image](https://cloud.githubusercontent.com/assets/10420662/15230527/d8cafa22-189e-11e6-9059-1dd11fc1632c.png)

**Comment by jonwhittlestone** [comment]
Yes, I did get the Postman collection going (what a wonderful feature of the tool)

Here's a generated token - https://www.dropbox.com/s/valfjalqvngxaj6/Screenshot%202016-05-12%2022.25.57.png?dl=0

And then here's my postman request - I still get unauthorised, surely there's something I'm missing. I'm serving it with Laravel Valet, and on OSX I've got PHP7.0 going..

POST /api/v1/posts HTTP/1.1
Host: limoncello-collins.dev
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json
Authorization: qbFeIaNjpvnQC0sJ
Cache-Control: no-cache
Postman-Token: 20e74228-7ca4-9750-2a33-6fb4b1e4d22d

{
    "data": {
        "type": "posts",
        "id"  : null,
        "attributes": {
            "title" : "Post title",
            "text"  : "Post text"
        },
        "relationships": {
            "board": {
                "data": { "type": "boards", "id": "1" }
            }
        }
    }
}

**Comment by jonwhittlestone** [comment]
I have progressed passed the above response 'Unauthorised' I wasn't including the title and text fields in the body correctly. However as you can see, I'm not getting 400 - Bad Request, and a response of: 

```
{
  "errors": [
    {
      "title": "Invalid element.",
      "source": {
        "pointer": "/data/type"
      }
    }
  ]
}
```

It seems to be [erroring out here](https://github.com/neomerx/limoncello/blob/develop/src/Api/Crud.php#L163). One thing is that I've noticed is that this is using the develop branch, is this correct?

<img width="1192" alt="screenshot 2016-05-13 08 35 19" src="https://cloud.githubusercontent.com/assets/1681212/15241100/b0381bb6-18e5-11e6-8c53-34256d05e952.png">

**Comment by neomerx** [comment]
I can spot you send data as `x-www-form-...` instead of `raw` json as in original postman collection.

what I do locally

``` bash
$ git clone https://github.com/neomerx/limoncello-collins && cd limoncello-collins
$ composer install && composer docker-up
```

it thinks for a couple of minutes and its logs ends with

```
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
Compiling common classes
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
> docker-compose up -d
Starting db_collins
Starting logs_collins
Recreating fpm_collins
Recreating web_collins
> echo waiting 10s && sleep 10s
waiting 10s
> docker-compose run --rm fpm php artisan migrate:reset && docker-compose run --rm fpm php artisan migrate && docker-compose run --rm fpm php artisan db:seed
Rolled back: 0000_01_01_000000_Initial
Migrated: 0000_01_01_000000_Initial
Seeded: Neomerx\LimoncelloIlluminate\Database\Seeds\SeedRoles
Seeded: Neomerx\LimoncelloIlluminate\Database\Seeds\SeedUsers
Seeded: Neomerx\LimoncelloIlluminate\Database\Seeds\SeedBoards
Seeded: Neomerx\LimoncelloIlluminate\Database\Seeds\SeedPosts
Seeded: Neomerx\LimoncelloIlluminate\Database\Seeds\SeedComments
```

now my `http://localhost:8080/` shows default home page

Let's go to API stuff

I'm opening postman with **unmodified original** collection and get token
![image](https://cloud.githubusercontent.com/assets/10420662/15244825/c5276c40-190b-11e6-9e20-6adda9bf397e.png)

and then click on 'Posts->Create post' **without any modifications of settings and input data** then I click 'Send' button and get

![image](https://cloud.githubusercontent.com/assets/10420662/15244885/21edf642-190c-11e6-879d-a391a1876dc7.png)

cleaning (stop docker servers)

``` bash
~/limoncello-collins$ composer docker-down
```

output

```
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
> docker-compose down
Stopping web_collins ... done
Stopping fpm_collins ... done
Stopping logs_collins ... done
Stopping db_collins ... done
Removing web_collins ... done
Removing fpm_collins ... done
Removing logs_collins ... done
Removing db_collins ... done
```

**Comment by jonwhittlestone** [comment]
Thanks for your help, am keen to try this library.

So, I've brought up your docker containers with how you've said. I like the way you've specified a way to bring docker up in composer, I might have to use that technique in future.

My docker-machine IP is 192.168.99.100. So I specify this on port 8080, rather than localhost as that's being used by other containers for other projects.

When I follow the steps you've indicated above, I can get the auth token fine.

When I select the Create POST collection, you say 'unmodified' but don't I have to enter the received auth token in the HEADERS(3) tab?

<img width="1195" alt="screenshot 2016-05-13 15 10 53" src="https://cloud.githubusercontent.com/assets/1681212/15250502/0219bf98-191d-11e6-8b13-58250023e97c.png">

**Comment by neomerx** [comment]
No, you don't need to enter it manually. It would be taken from environment variables

![image](https://cloud.githubusercontent.com/assets/10420662/15252025/c5b0386c-1934-11e6-9c21-77f23fbefc7d.png)

{{token}} means 'take variable from environment' which we placed during 'get token' step.

**Comment by jonwhittlestone** [comment]
But I still get unauthorized :( - unless I need to actually include the prefix 'Bearer'

<img width="1189" alt="screenshot 2016-05-13 16 10 35" src="https://cloud.githubusercontent.com/assets/1681212/15252353/56c6d65e-1925-11e6-917a-95d1558149ba.png">

<img width="1193" alt="screenshot 2016-05-13 16 12 18" src="https://cloud.githubusercontent.com/assets/1681212/15252388/7c5e6d28-1925-11e6-91d1-46ae25ef4875.png">

**Comment by neomerx** [comment]
Yes, [Bearer](https://tools.ietf.org/html/rfc6750) is needed. Though I can't understand why you try to edit these fields manually...

**Comment by jonwhittlestone** [comment]
Okay thanks, I was missing a point with your instructions. Since the URL title contained curly braces {{server}}, I thought the Bearer {{token}} meant that I need to manually enter the auth string returned from the /authorization route.

Solved, thanks for your help.

**Comment by neomerx** [comment]
There is 'Manage Environments' feature in postman. Basically it works same way as {{token}}. You can assign {{server}} to localhost/staging/prod and single postman collection and easily switch between server. Can you see 'limoncello' in top right corner of the very first screenshot? This is it. Try it out, I'm sure you would like it :wink:
